version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_rest-calculadora-energia
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - TZ=America/Sao_Paulo
